name: Make VENV cache

on: workflow_dispatch

env:
  # This one should mirror the one in utils/constants.py and .gitignore
  VENV_CACHE_DIR_NAME: THE_VENV_CACHE

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Try to restore the VENV cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.VENV_CACHE_DIR_NAME }}
          key: key-${{ env.VENV_CACHE_DIR_NAME }}

      - name: "VENV cache not found: Make VENV cache"
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          chmod +x utils/make_venv_cache.sh
          utils/make_venv_cache.sh

      - name: "VENV cache not found: Save VENV cache"
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ${{ env.VENV_CACHE_DIR_NAME }}
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}