name: Mandelbrot set

on:
  schedule:
    - cron: '15 */2 * * *'
  workflow_dispatch:

env:  # Note: changing these values will require changes in other parts of the code, so it's better to avoid it if possible.
  FRACTAL_NAME: MandelbrotSet
  VENV_CACHE_DIR_NAME: THE_VENV_CACHE  # note, if you update this don't forget to update it too in the other place in the project that using this value.

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.VENV_CACHE_DIR_NAME }}
          key: key-${{ env.VENV_CACHE_DIR_NAME }}
      
      - if: steps.restore-cache.outputs.cache-hit != 'true'
        run: exit 1

      - run: |  # render and post
          source $GITHUB_WORKSPACE/$VENV_CACHE_DIR_NAME/bin/activate
          python . "$FRACTAL_NAME"
        env:
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}

      - uses: actions/checkout@v4
        with:
          ref: fractal_metadata_20240226

      - run: |
          python save_the_md_file.py

          git config user.name "$FRACTAL_NAME"
          git config user.email "${{ vars.GIT_EMAIL }}"
          git add .
          git commit -m "$FRACTAL_NAME — $(date +'%Y %b %e, %l:%M %p')"
          
          echo "INFO: Attempt the first git push"
          git push

          if [ $? -ne 0 ]; then  # Rerun if the first pull fails, just in case there are multiple workflows pushing at nearly the same time.
            echo "INFO: Attempt the second git push"
            git pull
            git push
          fi
