import random


def get_random_fractal_greeting(day, fractal):
    random_greetings = [
        f'Happy {day}!',
        f'How\'s your day?',  # yes, it's "day", not `{day}`
        f'Enjoy your {day}!',
        f'{day} vibes!',
        f'Have an awesome {day}!',
        f'Wishing you a fantastic day!',
        f'Hey there, it\'s {day}!',
        f'Let\'s rock this {day}!',
        f'Having a blast on {day}?',
        f'Wishing you a rad {day}!',
        f'Hope you\'re having a great {day}!',
        f'Smile, it\'s {day}!',
        f'Keep shining on {day}!',
        f'Let\'s make it a memorable {day}!',
        f'Cheers to an incredible {day}!',
        f'Hope your {day} is awesome!',
        f'Sending you good vibes on this {day}!',
        f'Let the magic of {day} fill your heart!',
        f'You rock, and so does this {day}!',
        f'Shine bright like the sun on this {day}!',
        f'Wishing you a wonderful {day}!',
        f'Let this {fractal} inspire your {day}.',
        f'Happy {day}! Enjoy the beauty of {fractal}.',
        f'Warm wishes for your {day} filled with {fractal}.',
        f'{fractal} vibes to brighten your {day}.',
        f'Ever heard of this {fractal}?',
        f'Surprise! It\'s a {fractal}!',
        f'Good {day}! This {fractal} is awesome!',
        f'Wishing you a joyful day!',
        f'Another {day}, another {fractal}!',
        f'Feeling the {fractal} vibes today!',
        f'Smile on this lovely day!',
        f'Guess what? It\'s {fractal}!',
        f'Have a great day!',
        f'Feeling good today!',
        f'Wishing you the best!',
        f'Sending positive vibes!',
        f'Keep smiling!',
        f'Chin up, better times are coming!',
        f'Tough times don\'t last forever!',
        f'Life is tough, but so are you!',
        f'Chin up, lovely humans!',
    ]
    return random.choice(random_greetings)