name: Run unittest

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: check commit author
        id: check
        if: ${{ !startsWith(github.event.commits[0].author.name, 'tweet_') }}
        run: echo "run-tests=true" >> $GITHUB_OUTPUT
      
      - name: Checkout
        if: steps.check.outputs.run-tests
        uses: actions/checkout@v3

      - name: Run tests
        if: steps.check.outputs.run-tests
        run: |
          python -m unittest -v
