on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - run: |
          sudo apt update -qq > /dev/null 2>&1 && sudo apt install -qq ffmpeg > /dev/null 2>&1
          pip install -q numba==0.55.2 numpy==1.22.4 tweepy==4.14.0
          ls
          python .
          ls
        env:
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
