name: Test tweepy

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        env:
          FAKE_SECRETS: ${{ secrets.TEST_FAKE_SECRETS }}
        run: |
          echo "foo bar"
          echo "fake secrets: '$FAKE_SECRETS'"
