name: Scheduled Workflow
on:
  schedule:
    - cron: '*/7 * * * *' # Runs every 5 minutes
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My step
        run: echo "Hello, world!"
