name: Test tweepy

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        env:
          FAKE_SECRETS: ${{ secrets.TEST_FAKE_SECRETS }}
        shell: python
        run: |
          x = '$FAKE_SECRETS'
          print(x)
          print(repr(x))
