name: tweet_mandelbrot (Hourly fractals)

on:
  schedule:
    - cron: '15 */2 * * *'
  workflow_dispatch:

env:
  FRACTAL_NAME: Mandelbrot Set
  # This one should mirror the one in utils/constants.py and .gitignore
  VENV_CACHE_DIR_NAME: THE_VENV_CACHE

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      
      - name: Try to restore the VENV cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.VENV_CACHE_DIR_NAME }}
          key: key-${{ env.VENV_CACHE_DIR_NAME }}
      
      - name: VENV cache not found
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: Tweet!
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY_2 }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY_2 }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN_2 }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET_2 }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        run: |
          source $GITHUB_WORKSPACE/$VENV_CACHE_DIR_NAME/bin/activate
          python tweet_mandelbrot

      - name: Checkout metadata branch
        uses: actions/checkout@v3
        with:
          ref: fractal-metadata

      - name: Archiving
        run: |
          python archive_manager.py

          git config user.name "$FRACTAL_NAME"
          git config user.email "${{ vars.GIT_EMAIL }}"
          git add .
          git commit -m "$FRACTAL_NAME — $(date +'%Y %b %e, %l:%M %p')"
          
          echo "INFO: Attempt the first git push"
          git push

          # Just in case there are multiple workflows pushing at nearly the same time
          if [ $? -ne 0 ]; then
            # Repush if the first pull failed
            echo "INFO: Attempt the second git push"
            git pull
            git push
          fi